import 'package:flutter/material.dart';

import 'skin_seeds.dart';
import 'skins.dart';
import 'tokens.dart';

/// The seeds each shipped skin is made of.
///
/// In `lib` rather than in its test for two reasons. The gallery duplicates a
/// built-in into a new data skin, which means the app itself needs these — and
/// keeping the table here makes `skin_seeds_test.dart` prove the *shipped*
/// seeds reproduce the *shipped* skins, rather than proving a test-local copy
/// reproduces them, which would be a weaker claim wearing the same words.
const builtInSeeds = <HcSkin, SkinSeeds>{
  HcSkin.midnight: SkinSeeds(
    name: 'midnight',
    brightness: Brightness.dark,
    ground: Color(0xFF0B0E13),
    raised: Color(0xFF141922),
    sunken: Color(0xFF0D1116),
    overlay: Color(0xFF1A202A),
    ink: Color(0xFFE9EDF2),
    inkMuted: Color(0xFF8B95A4),
    accent: Color(0xFF7CC4FF),
    onAccent: Color(0xFF06131F),
    active: Color(0xFFFFB661),
    inactive: Color(0xFF2A313B),
    success: Color(0xFF6FD1A6),
    warn: Color(0xFFFFC978),
    danger: Color(0xFFFF7B72),
    offline: Color(0xFFAA737A),
    hairline: Color(0xFF262D38),
    corners: (4, 8, 14, 22),
    spaceUnit: 8,
    typeScale: 1,
    glowStrength: 1,
    glowRadius: 34,
    density: SkinDensity.comfortable,
    motion: SkinMotion.standard,
  ),
  HcSkin.ambientGlass: SkinSeeds(
    name: 'ambient_glass',
    brightness: Brightness.dark,
    ground: Color(0xFF0B0D10),
    raised: Color(0xFF14181D),
    sunken: Color(0xFF080A0C),
    overlay: Color(0xFF161A20),
    ink: Color(0xFFF2F5F8),
    inkMuted: Color(0xFF8D97A3),
    accent: Color(0xFF7CC4FF),
    onAccent: Color(0xFF06131F),
    active: Color(0xFFFFB661),
    inactive: Color(0xFF3A424D),
    success: Color(0xFF5FD6A2),
    warn: Color(0xFFFFC978),
    danger: Color(0xFFFF7B72),
    offline: Color(0xFFA07680),
    hairline: Color(0x1FFFFFFF),
    corners: (5, 10, 18, 26),
    spaceUnit: 8,
    typeScale: 1.15,
    glowStrength: 1,
    glowRadius: 44,
    density: SkinDensity.wall,
    motion: SkinMotion.calm,
    glass: SkinGlass.frosted,
  ),
  HcSkin.controlRoom: SkinSeeds(
    name: 'control_room',
    brightness: Brightness.dark,
    ground: Color(0xFF08090A),
    raised: Color(0xFF0F1114),
    sunken: Color(0xFF050607),
    overlay: Color(0xFF131619),
    ink: Color(0xFFE6E9ED),
    inkMuted: Color(0xFF7A828C),
    accent: Color(0xFF38BDF8),
    onAccent: Color(0xFF04141D),
    active: Color(0xFFFBBF24),
    inactive: Color(0xFF2A2F35),
    success: Color(0xFF34D399),
    warn: Color(0xFFD97706),
    danger: Color(0xFFF87171),
    offline: Color(0xFFB3666E),
    hairline: Color(0xFF1E2126),
    corners: (2, 3, 5, 8),
    spaceUnit: 6,
    typeScale: 0.92,
    glowStrength: 0,
    glowRadius: 0,
    density: SkinDensity.compact,
    motion: SkinMotion.crisp,
    // Control Room names its own sensor hues: the shared palette is tuned for
    // a bloom this skin does not have.
    metric: HcMetricTints(
      temperature: Color(0xFFFB923C),
      humidity: Color(0xFF22D3EE),
      illuminance: Color(0xFFFDE047),
      co2: Color(0xFF34D399),
      power: Color(0xFFFBBF24),
      reading: Color(0xFF38BDF8),
    ),
  ),
  HcSkin.softHome: SkinSeeds(
    name: 'soft_home',
    brightness: Brightness.light,
    ground: Color(0xFFF7F4EF),
    raised: Color(0xFFFFFFFF),
    sunken: Color(0xFFEFEAE2),
    overlay: Color(0xFFFFFFFF),
    ink: Color(0xFF241F1A),
    inkMuted: Color(0xFF706861),
    accent: Color(0xFFA65135),
    onAccent: Color(0xFFFFFFFF),
    active: Color(0xFF925E11),
    inactive: Color(0xFFD8D0C6),
    success: Color(0xFF447359),
    warn: Color(0xFF915C1C),
    danger: Color(0xFFC0524B),
    offline: Color(0xFF936C6F),
    hairline: Color(0xFFE2DACE),
    corners: (6, 12, 20, 28),
    spaceUnit: 8,
    typeScale: 1,
    glowStrength: 0.35,
    glowRadius: 26,
    density: SkinDensity.comfortable,
    motion: SkinMotion.standard,
    glass: SkinGlass.tinted,
    focus: Color(0xFFC2603F),
    densityOverride: HcDensity(
        rowHeight: 56, controlHeight: 48, minTapTarget: 48, cardPadding: 18),
    motionOverride: HcMotion(
      fast: Duration(milliseconds: 130),
      base: Duration(milliseconds: 260),
      slow: Duration(milliseconds: 420),
      curve: Curves.easeOutCubic,
      emphasized: Curves.easeOutBack,
      enabled: true,
    ),
    // A light ground needs darker sensor hues than any accent-derived value.
    metric: HcMetricTints(
      temperature: Color(0xFF803B1E),
      humidity: Color(0xFF266C87),
      illuminance: Color(0xFF74570B),
      co2: Color(0xFF2D7B5B),
      power: Color(0xFF5C370A),
      reading: Color(0xFF2F4774),
    ),
  ),
};
