/// One design, stamped out once per device.
///
/// The last thing on the designer's list, and the honest fix for the worst
/// number in it: sixteen real pages carried **forty-nine hand-placed light
/// toggles**, because there was no way to say *this row, for the lights in this
/// room*. Those pages were generated by a Python script doing arithmetic, which
/// is the clearest possible statement that the tool could not do the job.
///
/// **A tool, not a construct.** Nothing in the document says "repeated". This
/// stamps out real elements, wired to real devices, and then they are ordinary
/// elements you drag, restyle and delete one at a time — the same contract
/// templates and named styles follow, and for the reason John gave about both:
/// *"applied and then able to be customized. That is the whole point of a
/// custom designer"*. A live repeater would be the fourth propagation
/// mechanism proposed and the fourth one turned down.
///
/// So the row you drew is the first row rather than a master of it: [repeatFor]
/// re-wires the design itself to the first device and copies it for the rest.
/// Six lights give six rows, not a template plus six.
///
/// Pure, like the rest of this family. What the editor does with the result is
/// `page_screen`'s business; what a copy *is* is decided here, where it can be
/// tested without pumping a widget.
library;

import '../models/device_state.dart';
import '../models/dashboard.dart';
import 'device_slot.dart';
import 'grid_engine.dart';
import 'groups.dart';
import 'widget_registry.dart';

/// The result: the originals re-wired, and the copies to add.
typedef Repeated = ({
  /// The design itself, pointed at the first device. Same ids, same places.
  Map<String, DashboardWidgetModel> rewired,

  /// The copies, by their new ids.
  Map<String, DashboardWidgetModel> widgets,

  /// Where the copies go, in page units.
  List<GridItem> items,
});

/// [design] repeated once per device in [devices].
///
/// [items] are the design's placements in page coordinates, and [step] is how
/// far each copy sits from the one before it — the caller works that out from
/// the design's own bounding box, because "one row below" means the row's
/// height plus whatever gap looks right, and neither is this function's
/// business.
///
/// **Only widgets that name a device are re-wired.** A heading inside the row
/// that says "Lights" stays saying "Lights"; a toggle becomes that light. The
/// rule is the registry's `deviceRef` fields, which is the same list the wiring
/// panel and `unwireAll` walk, so a repeated page is wired exactly the way a
/// hand-wired one is.
///
/// **And retitled to match**, because a row named for its device is the whole
/// reason the layer tree and the wiring panel are readable. Again only where
/// there was a device to speak of: nothing else is touched.
///
/// Groups are suffixed rather than shared. A row that was `Panel/Row` gives
/// `Panel/Row 2`, `Panel/Row 3` — two rows in one group would move as one
/// thing, which is not what a list of rows is.
Repeated repeatFor({
  required List<DashboardWidgetModel> design,
  required List<GridItem> items,
  required List<DeviceState> devices,
  required ({double dx, double dy}) step,
  required String Function(int index) stamp,
  Set<String> takenPaths = const {},
}) {
  if (design.isEmpty || devices.isEmpty) {
    return (rewired: const {}, widgets: const {}, items: const []);
  }

  final byId = {for (final w in design) w.id: w};
  final rewired = {
    for (final w in design) w.id: _wired(w, devices.first),
  };

  final widgets = <String, DashboardWidgetModel>{};
  final copies = <GridItem>[];
  final claimed = {...takenPaths};
  var n = 0;

  for (var index = 1; index < devices.length; index++) {
    final device = devices[index];
    // One rename per distinct path per copy, decided before the members are
    // walked, so two elements of the same row land in the *same* new group
    // rather than in two — the rule `pasteInto` follows, for the same reason.
    final renamed = <String, String>{};
    for (final w in design) {
      final path = groupOf(w.config);
      if (path == null || renamed.containsKey(path)) continue;
      final next = uniqueName(path, claimed);
      // `uniqueName` answers a leaf name; a nested design keeps its parent.
      final parent = parentOf(path);
      final full = parent == null ? next : '$parent$groupSeparator$next';
      renamed[path] = full;
      claimed.add(next);
    }

    for (final item in items) {
      final source = byId[item.id];
      if (source == null) continue;
      final id = stamp(n++);
      final path = groupOf(source.config);
      final wired = _wired(source, device);
      widgets[id] = wired.copyWith(
        id: id,
        config: withGroup(wired.config, path == null ? null : renamed[path]),
      );
      copies.add(GridItem(
        id: id,
        x: item.x,
        y: item.y,
        w: item.w,
        h: item.h,
        minW: item.minW,
        minH: item.minH,
        floating: item.floating,
        z: item.z,
        rotation: item.rotation,
        opacity: item.opacity,
        rect: item.rect?.copyWith(
          x: item.rect!.x + step.dx * index,
          y: item.rect!.y + step.dy * index,
        ),
      ));
    }
  }

  return (rewired: rewired, widgets: widgets, items: copies);
}

/// [widget] pointed at [device], or unchanged when it names no device.
DashboardWidgetModel _wired(DashboardWidgetModel widget, DeviceState device) {
  final descriptor = WidgetRegistry.lookup(widget.type);
  if (descriptor == null) return widget;
  var config = widget.config;
  var touched = false;
  for (final field in descriptor.configFields) {
    if (field.kind != WidgetConfigKind.deviceRef) continue;
    config = wire(config, field.name, device.id);
    touched = true;
  }
  if (!touched) return widget;
  return widget.copyWith(config: config, title: device.displayName);
}

/// How far apart the copies should sit, given what is being repeated.
///
/// The design's own bounding box plus a gap, on whichever axis was asked for.
/// Down by default because a list of devices is a list: rows going across run
/// off the page at six of them, and six is the ordinary case.
({double dx, double dy}) stepFor(
  Iterable<GridItem> items, {
  bool across = false,
  double gap = 8,
}) {
  var width = 0.0;
  var height = 0.0;
  var seen = false;
  var left = 0.0, top = 0.0, right = 0.0, bottom = 0.0;
  for (final item in items) {
    final rect = item.rect;
    if (rect == null) continue;
    if (!seen) {
      seen = true;
      left = rect.x;
      top = rect.y;
      right = rect.right;
      bottom = rect.bottom;
      continue;
    }
    if (rect.x < left) left = rect.x;
    if (rect.y < top) top = rect.y;
    if (rect.right > right) right = rect.right;
    if (rect.bottom > bottom) bottom = rect.bottom;
  }
  if (seen) {
    width = right - left;
    height = bottom - top;
  }
  return across ? (dx: width + gap, dy: 0.0) : (dx: 0.0, dy: height + gap);
}
